{% set version = "0.2-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-getpass
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/getPass_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/getPass/getPass_{{ version }}.tar.gz
  sha256: 15dbebf8b46814e6e4cf9affb83439b253477900b1159d6f0c3a919fc44e1828

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rstudioapi               # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rstudioapi >=0.5
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rstudioapi >=0.5

test:
  commands:
    - $R -e "library('getPass')"           # [not win]
    - "\"%R%\" -e \"library('getPass')\""  # [win]

about:
  home: https://github.com/wrathematics/getPass
  license: BSD-2-Clause
  summary: A micro-package for reading "passwords", i.e.  reading user input with masking, so that the input is not displayed as it  is typed.  Currently we have support for 'RStudio', the command line (every OS), and any platform where 'tcltk' is present.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause
    - {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
