appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: gKjU5aUJK2VtGSx9RA4+phSMBzf2Ialsa0KBQHUF/ibSgygFCF63Tm3BXIAH+j8cRNA97SjpXFkr8Lj9dlTa2PLqUNrbVX/6y68JVDCGjSc/VQkYWcHMkxpyRW/E49wV33YSUsHOp3j76xyNqVWI7igNKnstHpq3Ca/mKvmfHhnq1BKPtPUx4JqHIu1V/obnAoWndp40PUV5NkCPnEDeguPB+mKzm762IWqbJn914/47ER8G0WPw9I+yzKESaqRLsMAUctamm3P2XkQN8FdsZ+cxyUjDc6pbeCvDSjmsmqzfF475TA+V6OzsPIIrlC2MHXsdY02zj5sE41n2XCn9iJpC5in3Cqu8FR2O0curYVMStHdd15iaCkFCEyVM2j0IeWpz5e2uy9mB3ZBwieUhCnrq2JgFQF34Klb0Ju9fhZ8J6tcQjgxd82HJlS+YXtpQGKOSQOQUMn6yDGIIVPUltAYZnQyx9e8BEaqaSTYmvaMX0CCqaB2B6OHpAq6ztNDKHBPrWx04mR8psMxS4UGq/CPRs/snW4On1/68bvE9ULHihAC5PvuG13Bz0VP3rYENo4Whcb6h0gMqm5Bqlz2v3EYUSXKRf3HFJkgckHPH5QN15pnvZ3GBuualnkb52cLm2dRzKNCAHE0Klimm3d3wp4uSi/LLIC8urpaQSDH0tlQ=}
