travis:
  secure:
    BINSTAR_TOKEN: hmkpaRirQt0mMp5cXnOf5LVnJW2UlO4k9pqpfB7CGeKDNGX4jsHJhrrGYoyQ7L9MwjXtH6vh3AI2PlYy+y7eKGsHUy+RKVMrW2XkUVHAd0iUXizWyzDQEuMrtvVGetLeYWFOG4vhM1VjUYGoca8BrGrslwGSOjfOrXR/lq85Vb9BLkbJKotSOOeUS8tm3fQs//DrXVjR+SVP2k061DKneTJOsIkOgjpAX2QTRaYN5MJqoL7N7WU7Pr1U9Hn2gHfXoo5IwX/s/hNjUzPaUB5JdonIntFJ+iP8zV/bDxhI/RasUFpRvw95XBhCbRRrMXQQlm6PXfqvVxH2lRWPXPzICMMd2zDpTGLyvVgAcKJ5ASLoUF8wIx6spcyuYwkMZiHN904wdQJca5Y61mvNYRdstBiRVWgLUH3/RkFq4PfshAN8Erx8WRH2hlExJ4DvOMEdbtJHQb7AVqmRvxxP4iZkoWcRxQttaxbLEy5EfMO5MVX6zu1o+0cpJbxDze647RclH0II/40o/9MvmzFaSXVbLrAi+njrX35NH68TP7TCEGkywV+DDYb0kM4q9G+pJBP/dVxAE+ChqO0CePwaF7O1ZtsRzwYNQEVPSgbpI/qbFaXeaJOzOMNjkUZOt7/sPRCya0N7pmW/z2HSN0GMfQvYBCg6aiJKB8PLq8LJhv8WPaU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
